server:
  image: sjoerdmulder/teamcity
  restart: always
  ports:
   - "8111:8111"
  volumes:
   - "/opt/teamcity/:/var/lib/teamcity"

agent1:
  build: teamcity-agent-docker
  privileged: true
  restart: always
  volumes:
   - "/opt/docker/agent1/:var/lib/docker"
  ports:
   - "9090:9090"
  environment:
   - TEAMCITY_SERVER=http://server:8111
  links:
   - server

agent2:
  build: teamcity-agent-docker
  restart: always
  privileged: true
  volumes:
   - "/opt/docker/agent1/:var/lib/docker"
  ports:
   - "9091:9090"
  environment:
   - TEAMCITY_SERVER=http://server:8111
  links:
   - server

