FROM sjoerdmulder/teamcity-agent:latestsjoerdmulder/teamcity-agent:latest
RUN curl -L https://github.com/harbur/captain/releases/download/v0.7.0/captain-`uname -s`-`uname -m` > /usr/local/bin/captain
RUN chmod +x /usr/local/bin/captain
